language: objective-c
osx_image: xcode9.2
env:
- DESTINATION="OS=11.1,name=iPhone 7" SCHEME="Forex" SDK=iphonesimulator

before_install:
- brew update
- brew outdated swiftlint || brew upgrade swiftlint
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project Forex.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project Forex.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
